name: Docker

on:
  push:
    branches: '*'
    tags: '*'
    paths:
      - '.gitmodules'
      - '.github/**'
      - 'src/**'
  pull_request:
    branches: "main"
    paths:
      - '.gitmodules'
      - '.github/**'
      - 'src/**'

env:
  BRANCH_NAME: ""
  BASE_SHA: ""


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run my action
      run: echo "This action runs if changes are not only in README or docs"
