name: Docker

on:
  push:
    branches: '*'
    tags: '*'
    paths:
      - '.gitmodules'
      - '.github/**'
      - 'src/**'
  pull_request:
    branches: "main"
    paths:
      - '.gitmodules'
      - '.github/**'
      - 'src/**'

env:
  BRANCH_NAME: ""
  BASE_SHA: ""


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "Branch name is ${GITHUB_REF##*/}"

        