name: Docker

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: "main"

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  LOWERCASE_IMAGE_NAME: ""


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run my action
        run: echo "This action runs if changes are not only in README or docs"