name: Docker

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: "main"

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  LOWERCASE_IMAGE_NAME: ""


jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_changes.outputs.skip }}  # 将输出设置为作业输出
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all files
        run: |
          echo "Listing all files in repository:"
          git ls-tree -r HEAD --name-only

      - name: Check for changes
        id: check_changes
        run: |
          echo "Checking for changes..."
          CHANGED_FILES=$(git diff --name-only HEAD)  # 直接与当前状态比较
          echo "Changed files: $CHANGED_FILES"
          
          if [ -z "$CHANGED_FILES" ] || [[ "$CHANGED_FILES" =~ ^(README\.md|docs/.*)$ ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT  # 设置输出
          else
            echo "skip=false" >> $GITHUB_OUTPUT  # 设置输出
          fi

  run-action:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.skip != 'true' }}  # 使用作业输出
    steps:
      - name: Run my action
        run: echo "This action runs if changes are not only in README or docs"